pipeline {
    agent {
        label 'bb5'
    }

    options {
        timestamps()
    }

    environment {
        DEPLOYMENT_ROOT = "/gpfs/bbp.cscs.ch/apps/hpc/test/jenkins/deployment"
        BASEDIR = "${DEPLOYMENT_ROOT}/deploy/spack/deploy"
    }

    stages {
        stage('Setup') {
            steps {
                dir("${DEPLOYMENT_ROOT}/deploy/spack") {
                    git(url: "https://github.com/BlueBrain/spack.git", branch: "deploy/test")
                }
                dir("${DEPLOYMENT_ROOT}/deploy/spack/etc/spack/licenses") {
                    git(url: "ssh://bbpcode.epfl.ch/user/kumbhar/spack-licenses")
                }
            }
        }

        stage('Compilers') {
            agent {
                label 'bb5-full'
            }

            steps {
                dir("${BASEDIR}") {
                    sh "./deploy.sh compilers"
                }
            }

            post {
                always {
                    archiveArtifacts artifacts: "stacks/compilers.xml"
                    junit testResults: "stacks/compilers.xml", allowEmptyResults: true
                }
            }
        }

        stage('Tools') {
            agent {
                label 'bb5-full'
            }

            steps {
                dir("${BASEDIR}") {
                    sh "./deploy.sh tools"
                }
            }

            post {
                always {
                    archiveArtifacts artifacts: "stacks/tools.xml"
                    junit testResults: "stacks/tools.xml", allowEmptyResults: true
                }
            }
        }

        stage('Libraries') {
            agent {
                label 'bb5-full'
            }

            steps {
                dir("${BASEDIR}") {
                    sh "./deploy.sh libraries"
                }
            }

            post {
                always {
                    archiveArtifacts artifacts: "stacks/libraries.xml"
                    junit testResults: "stacks/libraries.xml", allowEmptyResults: true
                }
            }
        }

        stage('Applications') {
            agent {
                label 'bb5-full'
            }

            steps {
                dir("${BASEDIR}") {
                    sh "./deploy.sh applications"
                }
            }

            post {
                always {
                    archiveArtifacts artifacts: "stacks/applications.xml"
                    junit testResults: "stacks/applications.xml", allowEmptyResults: true
                }
            }
        }

        stage('Deployment') {
            steps {
                sh "ls"
            }
        }
    }
}
